### ISSUE TITLE
OAuth2 로그인 기능 구현하기

### ISSUE THREAD

**Issue by kimgt0128** [kimgt0128/security-6-oauth2-JWT-hands-on-Spring-boot-3#1]
# 📌Feature Practice
>OAuth를 이용하여 로그인 API를 설계합니다.

# 📝To-do
- [ ] 스프링 시큐리티를 OAuth2를 이용하여 구글, 네이버, 카카오 로그인을 연동합니다.
- [ ] 간단한 유저 정보를 DB에 저장합니다.
- [ ] ClientRegistration 적용하기
- [ ] 기타 트러블 슈팅

   
# ✏️To-Study
- 간단한 구현 방식보다는 공부가 목적이므로 백엔드 책임 전담 방식으로 구현합니다.
  - 이후 프론트 전담 방식/프론트-백 분담 방식과 비교 각각의 장단점을 비교합니다.
  - 웹/앱/하이브리드앱 별로 맞는 방식을 고민해 봅니다.
- 시큐리티6 버전과 JWT 0.12.3을 기준으로 공부합니다.
- OAuth2의 확장 기능인 OIDC(Open ID Connect)방식을 공부합니다.
  - 일반적인 OAuth2와 OIDC 방식의 차이점을 공부합니다.
  - 두 방식의 차이점을 바탕으로 상황에 맞는 방식을 공부합니다.
