### ISSUE TITLE
JWT 기능 구현하기

### ISSUE THREAD

**Issue by kimgt0128** [kimgt0128/security-6-oauth2-JWT-hands-on-Spring-boot-3#4]
# 📌Feature Practice
>JWT를 발급하고 유저를 관리합니다.

# 📝To-do
- [ ] 로그인 성공시 JWT 발급
- [ ] 리프레쉬, 엑세스 토큰 발급
- [ ] 리프레시 토큰으로 엑세스 토큰 재발급
- [ ] RTR(Refresh Token Rotate) 방식 적용
- [ ] JWT 저장소 구현
- [ ] CORS 설정
- [ ] 기타 코드 리팩터링

   
# ✏️To-Study
- 공식 문서 권장 사항에 따라 쿠키 방식으로 JWT를 주고 받습니다.
- OAuth2 인증과 JWT 방식을 둘 다 사용할 때 신경써야 할 것을 확인합니다.
- 특히, OAuth2와 JWT에서 유저 정보를 가져오는 방식에 대해 익힙니다.
